language: c
- gcc
- clang
before_install:
- sudo pip install nose
- pip install conan
install:
- 
script:
- mkdir build
- cd build && conan install .. && cmake .. && cmake --build .
- nosetests ../test/tests.py