language: c
compiler:
  - gcc
before_install:
  - sudo pip install nose
  - sudo pip install conan
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x
  - sudo apt-get update
  - sudo apt-get upgrade
script:
  - mkdir build
  - cd build && conan install .. && cmake .. && cmake --build .
  - nosetests ../test/tests.py